{
    'name': 'Open HRMS Loan Accounting',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Open HRMS Loan Accounting',
    'description': 'Create accounting entries for loan requests.',
    'author': 'Cybrosys Techno Solutions,Open HRMS',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'live_test_url': 'https://youtu.be/NFZfiHyn0-0',
    'website': 'https://www.openhrms.com',
    'depends': [
        'hr_payroll_community',
        'hr',
        'account',
        'ohrms_loan',
    ],
    'data': [
        'security/ohrms_loan_accounting_security.xml',
        'views/res_config_settings_views.xml',
        'views/hr_loan_views.xml',
    ],
    'images': [
        'static/description/banner.jpg',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
