{
    'name': 'Open HRMS Official Announcements',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Manages Official Announcements',
    'description': 'This module helps you to manage HR official announcements',
    'live_test_url': 'https://youtu.be/VPh1A9-jM5Q',
    'author': 'Cybrosys Techno solutions,Open HRMS',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': ' https://cybrosys.com, https://www.openhrms.com',
    'depends': [
        'hr',
        'mail',
    ],
    'data': [
        'security/hr_announcement_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'views/hr_announcement_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_reward_warning_menus.xml',
    ],
    'images': [
        'static/description/banner.jpg',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
