"""
Tenant Suspension Routes — Páginas de suspensión y API de verificación de estado.

Flujo:
  1. Nginx consulta GET /api/tenant-status/{subdomain} para saber si el tenant está suspendido
  2. Si está suspendido, Nginx redirige internamente a /suspended/{type}?reason=...
  3. type = "owner" si el usuario es propietario (tiene cookie o token)
  4. type = "client" si es un visitante/cliente final

El archivo /etc/nginx/conf.d/suspended_tenants.conf contiene la lista
de tenants suspendidos generada por el script de sincronización.
"""
from fastapi import APIRouter, Request, Query, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from sqlalchemy.orm import Session
from typing import Optional
import hmac
import os
import json
import logging

from ..config import PROVISIONING_API_KEY, get_runtime_setting

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Suspension"])

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SUSPENDED_DIR = os.path.join(BASE_DIR, "static", "suspended")

# Archivo que contiene la lista de tenants suspendidos (generado por sync script)
SUSPENDED_LIST_FILE = os.path.join(BASE_DIR, "data", "suspended_tenants.json")


def _load_suspended_tenants() -> dict:
    """Carga la lista de tenants suspendidos desde archivo JSON."""
    try:
        if os.path.exists(SUSPENDED_LIST_FILE):
            with open(SUSPENDED_LIST_FILE, 'r') as f:
                return json.load(f)
    except Exception as e:
        logger.error(f"Error cargando suspended_tenants.json: {e}")
    return {}


def _save_suspended_tenants(data: dict):
    """Guarda la lista de tenants suspendidos en JSON."""
    os.makedirs(os.path.dirname(SUSPENDED_LIST_FILE), exist_ok=True)
    with open(SUSPENDED_LIST_FILE, 'w') as f:
        json.dump(data, f, indent=2, default=str)
    # También regenerar el mapa de Nginx
    _regenerate_nginx_map(data)


def _regenerate_nginx_map(data: dict):
    """
    Genera /etc/nginx/conf.d/suspended_map.conf con el mapa de tenants suspendidos.
    Formato:
        map $tenant_db $tenant_suspended {
            default 0;
            acme    1;
            demo    1;
        }
    """
    nginx_map_file = "/etc/nginx/conf.d/suspended_map.conf"
    lines = [
        "# Auto-generated by ERP Core — NO EDITAR MANUALMENTE",
        "# Regenerado cada vez que se suspende/reactiva un tenant",
        "map $tenant_db $tenant_suspended {",
        "    default 0;",
    ]
    for subdomain, info in data.items():
        if info.get("suspended", False):
            reason = info.get("reason", "payment").replace('"', '\\"')
            lines.append(f'    {subdomain} 1;')
    lines.append("}")
    lines.append("")

    # Mapa de razones (para el query param de la redirección)
    lines.append("map $tenant_db $suspension_reason {")
    lines.append('    default "payment_failed";')
    for subdomain, info in data.items():
        if info.get("suspended", False):
            reason = info.get("reason", "payment_failed")
            lines.append(f'    {subdomain} "{reason}";')
    lines.append("}")
    lines.append("")

    # Mapa de emails de propietarios (para detectar owner via cookie)
    lines.append("map $tenant_db $tenant_owner_email {")
    lines.append('    default "";')
    for subdomain, info in data.items():
        if info.get("suspended", False) and info.get("owner_email"):
            lines.append(f'    {subdomain} "{info["owner_email"]}";')
    lines.append("}")
    lines.append("")

    try:
        with open(nginx_map_file, 'w') as f:
            f.write("\n".join(lines))
        logger.info(f"✅ Nginx suspended map regenerado: {len(data)} entries")
        # Reload Nginx
        os.system("nginx -t && nginx -s reload 2>/dev/null || true")
    except PermissionError:
        logger.warning(f"⚠️ Sin permisos para escribir {nginx_map_file}")
    except Exception as e:
        logger.error(f"Error escribiendo nginx map: {e}")


def _require_api_key(x_api_key: str) -> None:
    expected = str(get_runtime_setting("PROVISIONING_API_KEY", PROVISIONING_API_KEY) or "").strip()
    if not expected or not x_api_key or not hmac.compare_digest(x_api_key, expected):
        raise HTTPException(status_code=401, detail="API key inválida")


# ─── Páginas HTML de suspensión ───────────────────────────────

@router.get("/suspended/owner", response_class=HTMLResponse)
async def suspended_owner_page(
    request: Request,
    reason: Optional[str] = Query(None, description="Razón de suspensión")
):
    """
    Página para el PROPIETARIO del sitio suspendido.
    Muestra opciones para actualizar pago y contactar soporte.
    """
    html_path = os.path.join(SUSPENDED_DIR, "owner.html")
    if not os.path.exists(html_path):
        return HTMLResponse("<h1>Servicio temporalmente no disponible</h1>", status_code=503)
    
    with open(html_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    return HTMLResponse(content=content, status_code=402)  # 402 Payment Required


@router.get("/suspended/client", response_class=HTMLResponse)
async def suspended_client_page(
    request: Request,
    reason: Optional[str] = Query(None, description="Razón de suspensión")
):
    """
    Página para VISITANTES/CLIENTES del sitio suspendido.
    Muestra mensaje amigable 'Estaremos de regreso pronto'.
    """
    html_path = os.path.join(SUSPENDED_DIR, "client.html")
    if not os.path.exists(html_path):
        return HTMLResponse("<h1>Estaremos de regreso pronto</h1>", status_code=503)
    
    with open(html_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    return HTMLResponse(content=content, status_code=503)  # 503 Service Unavailable


# ─── API de verificación de estado ────────────────────────────

@router.get("/api/tenant-status/{subdomain}")
async def get_tenant_status(subdomain: str):
    """
    Consulta rápida del estado de un tenant.
    Usado por Nginx via proxy_pass para decidir si servir Odoo o la página de suspensión.
    
    Retorna:
      - status: "active" | "suspended" | "unknown"
      - reason: razón de la suspensión
      - owner_email: email del propietario
    """
    data = _load_suspended_tenants()
    info = data.get(subdomain, {})
    
    if info.get("suspended", False):
        return {
            "subdomain": subdomain,
            "status": "suspended",
            "reason": info.get("reason", "payment_failed"),
            "owner_email": info.get("owner_email", ""),
            "suspended_at": info.get("suspended_at", "")
        }
    
    return {
        "subdomain": subdomain,
        "status": "active",
        "reason": None,
        "owner_email": None
    }


# ─── API de gestión de suspensión (admin) ─────────────────────

@router.post("/api/tenant-suspension/{subdomain}")
async def suspend_tenant(
    subdomain: str,
    reason: str = Query("payment_failed", description="Razón: payment_failed, past_due, cancelled, expired, manual"),
    owner_email: Optional[str] = Query(None, description="Email del propietario"),
    x_api_key: str = ""
):
    """
    Suspende un tenant — agrega a la lista de suspendidos y regenera Nginx map.
    
    Esto NO desactiva usuarios en Odoo (eso lo hace /api/provisioning/tenant/suspend).
    Esto controla la REDIRECCIÓN a nivel de proxy.
    """
    from datetime import datetime
    
    _require_api_key(x_api_key)
    
    data = _load_suspended_tenants()
    data[subdomain] = {
        "suspended": True,
        "reason": reason,
        "owner_email": owner_email or "",
        "suspended_at": datetime.utcnow().isoformat(),
    }
    _save_suspended_tenants(data)
    
    logger.info(f"🔴 Tenant {subdomain} suspendido: {reason}")
    
    return {
        "success": True,
        "subdomain": subdomain,
        "status": "suspended",
        "reason": reason,
        "message": f"Tenant {subdomain} suspendido. Nginx map regenerado."
    }


@router.delete("/api/tenant-suspension/{subdomain}")
async def reactivate_tenant(
    subdomain: str,
    x_api_key: str = ""
):
    """
    Reactiva un tenant — lo quita de la lista de suspendidos y regenera Nginx map.
    """
    _require_api_key(x_api_key)
    
    data = _load_suspended_tenants()
    if subdomain in data:
        del data[subdomain]
        _save_suspended_tenants(data)
        logger.info(f"🟢 Tenant {subdomain} reactivado")
    
    return {
        "success": True,
        "subdomain": subdomain,
        "status": "active",
        "message": f"Tenant {subdomain} reactivado. Nginx map regenerado."
    }


@router.get("/api/tenant-suspensions")
async def list_suspended_tenants(x_api_key: str = ""):
    """Lista todos los tenants actualmente suspendidos."""
    _require_api_key(x_api_key)
    
    data = _load_suspended_tenants()
    suspended = {k: v for k, v in data.items() if v.get("suspended", False)}
    
    return {
        "total": len(suspended),
        "tenants": suspended
    }
