{
    'name': 'Messengers',
    'summary': 'Messengers integration powered by UnitSoft',
    'category': 'Extra Tools',
    'images': [
        'static/description/messengers_image.png',
    ],
    'version': '19.0.3.0.2',
    'application': True,
    'author': 'UnitSoft',
    'support': '',
    'website': 'https://unitsoft.com.ua/',
    'license': 'OPL-1',
    'currency': 'EUR',
    'depends': [
        'base_automation',
        'mail',
        'queue_job',
        'base',
        'crm',
        'us_multichat',
    ],
    'external_dependencies': {'python': [], 'bin': []},
    'data': [
        'security/us_messenger_groups.xml',
        'security/ir.model.access.csv',
        'views/ir_logging_views.xml',
        'views/us_messenger_job_views.xml',
        'views/us_messenger_trigger_cron_views.xml',
        'views/us_messenger_trigger_automation_views.xml',
        'views/us_messenger_trigger_webhook_views.xml',
        'views/us_messenger_trigger_button_views.xml',
        'views/us_messenger_task_views.xml',
        'views/us_messenger_project_views.xml',
        'views/us_messenger_link_views.xml',
        'views/us_messenger_operator_views.xml',
        'wizard/us_messenger_mass_mailing.xml',
        'views/res_partner_views.xml',
        'views/mail_message.xml',
        'data/queue_job_function_data.xml',
        'views/us_messenger_menus.xml',
    ],
    'assets': {'web.assets_backend': ['us_messenger/static/src/core/common/*', 'us_messenger/static/src/core/web/*', 'us_messenger/static/src/views/**/*']},
    'qweb': [
    ],
    'auto_install': False,
    'installable': True,
}
