{
    'name': 'Vista Backend Theme',
    'version': '19.0.1.0.0',
    'category': 'Themes/Backend',
    'summary': 'Vista Backend Theme is an attractive theme for backend',
    'description': """Minimalist and elegant backend theme for Odoo 17, 
     Backend Theme, Theme""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': [
        'web',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/icons_views.xml',
        'views/layout_templates.xml',
        'views/theme_data_views.xml',
        'views/assets_views.xml',
        'data/theme_data.xml',
    ],
    'assets': {'web.assets_backend': {'/vista_backend_theme/static/src/js/chrome/sidebar_menu.js', '/vista_backend_theme/static/src/xml/systray_templates.xml', '/vista_backend_theme/static/src/scss/theme.scss', '/vista_backend_theme/static/src/xml/top_bar_templates.xml', '/vista_backend_theme/static/src/js/systray.js'}, 'web.assets_frontend': {'/vista_backend_theme/static/src/scss/login.scss'}},
    'images': [
        'static/description/banner.jpg',
        'static/description/theme_screenshot.jpg',
    ],
    'license': 'LGPL-3',
    'pre_init_hook': 'test_pre_init_hook',
    'post_init_hook': 'test_post_init_hook',
    'installable': True,
    'auto_install': False,
    'application': False,
}
